robots:
   -
      api_url : "https://www.example.com/api/v3/topics"
      bearer_token : "f35452af-8225-4ab5-b63d-9fcae6266d15"
      cid : 2
      title_content_type: "string" # ["url","string"]
      title_request_type: "get" # ['get','post']
      title : "test"
      text_content_type: "string" #["url","string"]
      text_request_type: "get" # ['get','post']
      text : "http://www.example.com/ge"
      time_type: "routine" #['routine','everyday',''everymonth'','once']
      time: "60" #[seconds,"h:m","day-h:m","month-day-h:m"] example: 86400  23:00 07-20:00  12-07-20:00